apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sedp-app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /spider
        pathType: Prefix
        backend:
          service:
            name: app-spider-staging-sedp-app
            port:
              number: 80
