apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sedp-app-ingress
  namespace: {{ .Values.appMode }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - web-app.sedp.tallturtle.network
      secretName: tls-vcluster-platform
  rules:
  - http:
      paths:
      - path: /spider
        pathType: Prefix
        backend:
          service:
            name: app-spider-{{ .Values.appMode }}-sedp-app
            port:
              number: 443
