apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sedp-app-ingress
  namespace: {{ .Values.appMode }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - web-app.{{ .Values.image.tag }}.sedp.tallturtle.network
      secretName: tls-vcluster-platform
  rules:
    - host: web-app.{{ .Values.image.tag }}.sedp.tallturtle.network
      http:
        paths:
        - path: /{{ .Values.name }}
          pathType: Prefix
          backend:
            service:
              name: {{ include "sample-app.fullname" . }}
              port:
                number: 443
